services:
  msisdn_api:
    image: rogier/msisdn_api:build
    container_name: msisdn_api-build
    build:
      args:
        SERVICE_NAME: msisdn_api
    environment:
      ENV: 'dev'
      NODE_ENV: 'dev'
    ports:
      - 3000:3000
    command: npm run start:dev
    volumes:
      - .:/var/service/
      - ./node_modules:/var/service/node_modules:cached

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1