services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: [.env-mongo, .env]
    restart: always
    networks:
      default:
        aliases:
          - mongodb.service.dev
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1