export enum ErrorCode {
  MSISDN_NOT_FOUND = 'MSISDN_NOT_FOUND',
  MSISDN_IN_USE_BY_OTHER_USER = 'MSISDN_IN_USE_BY_OTHER_USER',
  USER_ALREADY_HAS_DIFFERENT_MSISDN = 'USER_ALREADY_HAS_DIFFERENT_MSISDN',
}
